# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

test_that("importe_data_step works properly and show error if needed", {

  config <- yaml::read_yaml("C://workspace//gwilenalim//yaml//config.yml")
  
  dossier <- system.file(package = "gwilenalim")

    expect_true( importe_data_step(dossier) == "OK")

})

