# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

test_that("importe_redevances_industrie works", {
    config <- yaml::read_yaml("C://workspace//gwilenalim//yaml//config.yml")
  
    expect_true( importe_redevances_industrie() == "OK")
})
