# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' importe_stations_qualite
#' 
#' Fonction pour importer les coordonnées des stations qualité depuis le SANDRE et compléter le référentiel avec le référentiel AELB pour les réseaux d'appartenance. On se limite aux stations sur l'emprise du bassin de la Vilaine.
#' Réferentiel AELB disponible ici : https://donnees-documents.eau-loire-bretagne.fr/sites/donnees-documents/home/donnees/referentiel-stations-mesure-qualite.html
#' Référentiel métropolitain des stations ici : https://www.sandre.eaufrance.fr/atlas/srv/fre/catalog.search#/metadata/71767e88-a021-4e88-8787-5feed04958d6
#' 
#' @return
#' statut de l'enregistrement des données (OK si les lignes ont été importées et KO sinon)
#' @export
#' @examples
#' importe_stations_qualite()
importe_stations_qualite <- function(){
  # importe la couche de stations qualité de la métropole depuis le SANDRE
  
  
  # découpage de la couche importée selon l'emprise du bassin de la Vilaine
  
  
  
  # chargement de la couche de référence depuis le site AELB 
  
  
  # croisement avec ajout des informations RCS, RRP, RCO, RCR
  
  
}
