# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

#' sage_vilaine
#'
#' data in 'datasets'.
#'
#' @format A sf object with 1 row and 2 variables
#' \describe{
#'   \item{ nom }{  character }
#'   \item{ geom }{  sfc_MULTIPOLYGON }
#' }
#' @source https://sandre.eaufrance.fr/atlas/srv/fre/catalog.search#/metadata/2faf7c9e-ad62-4137-b80b-8b0caa3609cb
"sage_vilaine" 
